<?php

/**
 * @file
 * Provides a student entity type.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function student_catalog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.student_catalog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a student entity with additional features.') . '</p>';
      return $output;
  }
}
