<?php

/**
 * @file
 * Provides a student entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function student_catalog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.student_catalog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a student entity with additional features.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function student_catalog_theme() {
  return [
    'student' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for student templates.
 *
 * Default template: student.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the student information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_student(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

